// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybccdzjhdigeiqzxfoqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InliY2NkempoZGlnZWlxenhmb3F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDQ3NjYsImV4cCI6MjA3MTE4MDc2Nn0.VNgTn7bFGljBrLZ260_CI2Qi9QsWWyB-zghvsx1Q7NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});