// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouwocgljihksxuavwmho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91d29jZ2xqaWhrc3h1YXZ3bWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MTM5OTcsImV4cCI6MjA3MTA4OTk5N30.ChBjmA5aGQCqW0OIft50CiMokhb69gp2SGyPSJq0QfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});